    
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable

script: vendor/bin/phpunit tests